### ISSUE TITLE
ModelValidationError in benchmark.py

### ISSUE THREAD

**Issue by jwoehr** [Qiskit/qiskit-qcgpu-provider#12]
```
(qdev_env1) [jwoehr@power9-vm7 qiskit-qcgpu-provider]$ python3 benchmark.py --samples 15  --qubits 5 --single True
Traceback (most recent call last):
  File "benchmark.py", line 36, in <module>
    qcgpu_backend = QCGPUProvider().get_backend('statevector_simulator')
  File "/home/jwoehr/work/Qiskit/DEV/qiskit-qcgpu-provider/qiskit_qcgpu_provider/__init__.py", line 27, in __init__
    self._backends = self._verify_backends()
  File "/home/jwoehr/work/Qiskit/DEV/qiskit-qcgpu-provider/qiskit_qcgpu_provider/__init__.py", line 45, in _verify_backends
    backend_instance = backend_class(provider=self)
  File "/home/jwoehr/work/Qiskit/DEV/qiskit-qcgpu-provider/qiskit_qcgpu_provider/statevector_simulator.py", line 110, in __init__
    self.DEFAULT_CONFIGURATION)
  File "/home/jwoehr/work/Qiskit/DEV/qiskit-terra/qiskit/validation/base.py", line 353, in from_dict
    ex.messages, ex.field_names, ex.fields, ex.data, **ex.kwargs) from None
qiskit.validation.exceptions.ModelValidationError: {'coupling_map': ['Missing data for required field.']}
```

**Comment by adamisntdead** [comment]
This will be fixed in the next commit, the `DEFAULT_CONFIGURATION` was just missing a `'coupling_map': None`.
